# Change these first
owner: TAKK-Consulting # Your GitHub username
repo: status # Your GitHub repository name

i18n:
  locale: en-GB

# Add your sites here
sites:
  - name: TAKK Consulting
    url: https://www.takkconsulting.co.uk
  - name: CCD Burundi
    url: https://ccdburundi.org.uk
  - name: PlayWood Forest School
    url: https://playwoodforestschool.co.uk
  - name: Tim & Kathy
    url: https://www.timandkathy.co.uk
  - name: Bath City Pastors (website)
    url: https://bathcitypastors.org.uk/
  - name: Bath City Pastors (rota app)
    url: https://rota.bathcitypastors.org.uk/
  - name: BathNES Greens Humhub
    url: https://members.bathnesgreens.org.uk/
  - name: Lux Youth Project
    url: https://www.luxyouthproject.co.uk/
#  - name: Test for HEAD
#    method: HEAD
#    url: https://www.google.com
#  - name: Secret Site
#    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.takkconsulting.co.uk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TAKK Consulting Status Page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is our status page which uses **real-time** data from our [GitHub repository](https://github.com/TAKK-Consulting/status). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
